# Generated by Django 5.1.2 on 2025-02-11 22:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("ticker", models.CharField(max_length=10, unique=True)),
                ("quantity", models.PositiveIntegerField(default=0)),
                ("avg_price", models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Trade",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("ticker", models.CharField(max_length=10)),
                (
                    "trade_type",
                    models.CharField(
                        choices=[("buy", "Buy"), ("sell", "Sell")], max_length=5
                    ),
                ),
                (
                    "order_type",
                    models.CharField(
                        choices=[
                            ("Market Price", "Market Price"),
                            ("Limit Order", "Limit Order"),
                            ("Stop Order", "Stop Order"),
                            ("Stop-Limit Order", "Stop-Limit Order"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("price", models.FloatField()),
                ("stop_price", models.FloatField(blank=True, null=True)),
                ("time_in_force", models.CharField(default="Day", max_length=20)),
                ("executed_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
