# Generated by Django 5.1.2 on 2025-02-11 23:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trade",
            old_name="executed_at",
            new_name="timestamp",
        ),
        migrations.RemoveField(
            model_name="trade",
            name="time_in_force",
        ),
        migrations.AlterField(
            model_name="trade",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="trade",
            name="order_type",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="trade",
            name="quantity",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="trade",
            name="trade_type",
            field=models.CharField(
                choices=[("buy", "Buy"), ("sell", "Sell")], max_length=4
            ),
        ),
    ]
