# Generated by Django 5.1.2 on 2025-02-17 23:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_rename_executed_at_trade_timestamp_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Funds",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("available_margin", models.FloatField(default=100000.0)),
                ("used_margin", models.FloatField(default=0.0)),
                ("opening_balance", models.FloatField(default=100000.0)),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(max_length=10)),
                (
                    "trade_type",
                    models.CharField(
                        choices=[("buy", "Buy"), ("sell", "Sell")], max_length=4
                    ),
                ),
                ("order_type", models.CharField(max_length=20)),
                ("quantity", models.IntegerField()),
                ("price", models.FloatField()),
                ("status", models.CharField(default="pending", max_length=20)),
                ("placed_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(max_length=10, unique=True)),
                ("quantity", models.IntegerField(default=0)),
                ("avg_price", models.FloatField(default=0)),
                ("pnl", models.FloatField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name="trade",
            name="timestamp",
        ),
        migrations.AddField(
            model_name="portfolio",
            name="total_value",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="trade",
            name="executed_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
