# Generated by Django 5.1.2 on 2025-02-18 00:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_funds_order_position_remove_trade_timestamp_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(max_length=10, unique=True)),
                ("current_price", models.FloatField()),
                ("day_high", models.FloatField()),
                ("day_low", models.FloatField()),
                ("volume", models.BigIntegerField()),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="funds",
            name="leverage_used",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="funds",
            name="net_exposure",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="dividends_received",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="sector",
            field=models.CharField(default="General", max_length=50),
        ),
        migrations.AddField(
            model_name="position",
            name="carry_forward",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="position",
            name="leverage",
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name="position",
            name="risk_score",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="trade",
            name="status",
            field=models.CharField(default="Pending", max_length=20),
        ),
        migrations.AddField(
            model_name="trade",
            name="take_profit_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Executed", "Executed"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="trade",
            name="order_type",
            field=models.CharField(
                choices=[
                    ("market", "Market Price"),
                    ("limit", "Limit Order"),
                    ("stop", "Stop Order"),
                    ("stop-limit", "Stop-Limit Order"),
                ],
                max_length=20,
            ),
        ),
    ]
