# Generated by Django 5.1.2 on 2025-02-18 00:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_marketdata_funds_leverage_used_funds_net_exposure_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trade",
            old_name="executed_at",
            new_name="timestamp",
        ),
    ]
