# Generated by Django 5.1.2 on 2025-02-18 01:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_rename_executed_at_trade_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trade",
            name="quantity",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="trade",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Executed", "Executed"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
